# application.yml
app:
  version: 1.0.7

server:
  port: 8090

logging:
  level:
    root: debug
    com.besl: debug

spring:
  ai:
    ollama:
      chat:
        model: qwen2.5-coder:0.5b
      init:
        pull-model-strategy: always
        embedding:
          additional-models:
            - mxbai-embed-large
    ollama.base-url: http://localhost:11434


