-- Create CONFIG_METADATA_ITEM table if it doesn't exist
CREATE TABLE IF NOT EXISTS CONFIG_METADATA_ITEM (
    ID UUID NOT NULL PRIMARY KEY,
    EXTERNAL_ID VARCHAR(255),
    NAME VARCHAR(255) NOT NULL,
    METADATA_TYPE VARCHAR(255),
    IS_COLLECTION BOOLEAN DEFAULT FALSE,
    SORT_ORDER INT DEFAULT 0,
    FULL_PATH VARCHAR(1000),
    PARENT_ID UUID,
    PROJECT_ID UUID NOT NULL,
    VERSION INT NOT NULL
);

-- Create indexes if they don't exist
CREATE INDEX IF NOT EXISTS IDX_CMI_PROJECT ON CONFIG_METADATA_ITEM(PROJECT_ID);
CREATE INDEX IF NOT EXISTS IDX_CMI_PARENT ON CONFIG_METADATA_ITEM(PARENT_ID);
CREATE INDEX IF NOT EXISTS IDX_CMI_EXTERNAL_ID ON CONFIG_METADATA_ITEM(EXTERNAL_ID);
CREATE INDEX IF NOT EXISTS IDX_CMI_FULL_PATH ON CONFIG_METADATA_ITEM(FULL_PATH);

-- Create USER_EXTERNAL_ID table if it doesn't exist
CREATE TABLE IF NOT EXISTS USER_EXTERNAL_ID (
    ID UUID NOT NULL PRIMARY KEY,
    USER_ID UUID NOT NULL,
    EXTERNAL_ID VARCHAR(255) NOT NULL UNIQUE,
    SOURCE VARCHAR(255),
    DESCRIPTION VARCHAR(255),
    DATE_CREATED DATETIME
);

-- Create indexes for USER_EXTERNAL_ID
CREATE INDEX IF NOT EXISTS IDX_USER_EXTERNAL_ID_VALUE ON USER_EXTERNAL_ID(EXTERNAL_ID);
CREATE INDEX IF NOT EXISTS IDX_USER_EXTERNAL_ID_USER ON USER_EXTERNAL_ID(USER_ID);

-- Create PROJECT_EXTERNAL_ID table if it doesn't exist
CREATE TABLE IF NOT EXISTS PROJECT_EXTERNAL_ID (
    ID UUID NOT NULL PRIMARY KEY,
    PROJECT_ID UUID NOT NULL,
    EXTERNAL_ID VARCHAR(255) NOT NULL UNIQUE,
    SOURCE VARCHAR(255),
    DESCRIPTION VARCHAR(255),
    DATE_CREATED DATETIME
);

-- Create indexes for PROJECT_EXTERNAL_ID
CREATE INDEX IF NOT EXISTS IDX_PROJECT_EXTERNAL_ID_VALUE ON PROJECT_EXTERNAL_ID(EXTERNAL_ID);
CREATE INDEX IF NOT EXISTS IDX_PROJECT_EXTERNAL_ID_PROJECT ON PROJECT_EXTERNAL_ID(PROJECT_ID);
