name: Build Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: List files for debugging
      run: |
        echo "Current directory: $(pwd)"
        echo "Directory contents:"
        ls -la
        echo "Gradle directory contents:"
        ls -la gradle/wrapper/ || echo "gradle/wrapper directory not found"
        
    - name: Check if gradlew exists
      run: |
        if [ ! -f "gradlew" ]; then
          echo "ERROR: gradlew file not found!"
          echo "Available files:"
          find . -name "gradlew" -type f
          exit 1
        else
          echo "gradlew file found"
          ls -l gradlew
        fi
    
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Grant execute permission for gradlew
      run: |
        chmod +x gradlew
        ls -l gradlew
        
    - name: Validate Gradle wrapper
      run: |
        ./gradlew --version
        
    - name: Build with Gradle
      run: |
        echo "Starting Gradle build..."
        ./gradlew build -x test --info --stacktrace
        echo "Gradle build completed successfully"
      continue-on-error: true
      
    - name: Check build result and show logs
      run: |
        if [ -f "build/reports/tests/test/index.html" ]; then
          echo "Test reports found:"
          ls -la build/reports/tests/test/
        fi
        
        if [ -f "build.gradle" ]; then
          echo "Build.gradle exists"
        else
          echo "ERROR: build.gradle not found!"
        fi
        
        # Check if build was successful
        if ./gradlew tasks >/dev/null 2>&1; then
          echo "Gradle is working correctly"
        else
          echo "ERROR: Gradle is not working correctly"
          exit 1
        fi
        
    - name: Create Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        release_name: Release v${{ github.run_number }}
        draft: false
        prerelease: false
        
    - name: Upload JAR Artifact
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/libs/*.jar
        asset_name: commitet-jm.jar
        asset_content_type: application/java-archive